#!/usr/bin/env python3
import locale
locale.setlocale(locale.LC_ALL,'en_US.UTF-8')
import sys

for line in sys.stdin:
    parts = line.strip().split()
    new_parts = []
    for p in parts:
       new_parts.append(" ".join(p))
    print("{}".format(' <w> '.join(new_parts)))
    
    

